DBPath: _testhoddb
Buildings:
    soda: testbuildings/berkeley.ttl
    test: testbuildings/example.ttl
Ontologies:
    - "testbuildings/BrickFrame.ttl"
    - "testbuildings/Brick.ttl"
ReloadOntologies: false
DisableQueryCache: true
ShowNamespaces: false
ShowQueryPlan: false
ShowDependencyGraph: false
ShowQueryPlanLatencies: false
ShowOperationLatencies: false
ShowQueryLatencies: false
LogLevel: Critical
EnableBOSSWAVE: false
EnableHTTP: false
